name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install buildozer==1.5.0
          pip install cython==0.29.36

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git python3-dev ffmpeg libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev
          sudo apt-get install -y libffi-dev libssl-dev zlib1g-dev
          sudo apt-get install -y openjdk-17-jdk

      - name: Set up Android SDK
        run: |
          mkdir -p $HOME/android-sdk
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O commandlinetools.zip
          unzip commandlinetools.zip -d $HOME/android-sdk
          rm commandlinetools.zip
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$PATH:$ANDROID_HOME/cmdline-tools/bin
          yes | $ANDROID_HOME/cmdline-tools/bin/sdkmanager --sdk_root=$ANDROID_HOME "build-tools;33.0.0" "platforms;android-33" "platform-tools"
          echo "export ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "export PATH=$PATH:$ANDROID_HOME/cmdline-tools/bin" >> $GITHUB_ENV

      - name: Remove default Android SDK folder
        run: |
          sudo rm -rf /root/.android-sdk || true

      - name: Clean Buildozer cache
        run: |
          rm -rf $HOME/.buildozer || true
          rm -rf BratvaGame/.buildozer || true

      - name: Initialize Buildozer
        run: |
          cd BratvaGame
          buildozer init

      - name: Configure buildozer.spec
        run: |
          cd BratvaGame
          sed -i 's/title = My Application/title = Bratva 90s/' buildozer.spec
          sed -i 's/package.name = myapp/package.name = bratva/' buildozer.spec
          sed -i 's/package.domain = org.test/package.domain = org.bratva/' buildozer.spec
          sed -i 's/source.include_exts = py,png,jpg,kv,atlas/source.include_exts = py,png,jpg,mp3/' buildozer.spec
          sed -i 's/requirements = python3,kivy/requirements = python3,kivy/' buildozer.spec
          sed -i 's/#android.permissions = INTERNET/android.permissions = INTERNET/' buildozer.spec
          sed -i 's/android.api = 31/android.api = 33/' buildozer.spec
          sed -i 's/android.minapi = 21/android.minapi = 21/' buildozer.spec
          sed -i 's/#icon =/icon = images\/icon.png/' buildozer.spec
          sed -i 's/#android.sdk_path =/android.sdk_path = \/home\/runner\/android-sdk/' buildozer.spec
          sed -i 's/#android.ndk =/android.ndk = 23b/' buildozer.spec

      - name: Set Android SDK environment variables
        run: |
          export ANDROID_HOME=$HOME/android-sdk
          export ANDROID_SDK_ROOT=$HOME/android-sdk
          export PATH=$PATH:$ANDROID_HOME/cmdline-tools/bin
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
          echo "PATH=$PATH:$ANDROID_HOME/cmdline-tools/bin" >> $GITHUB_ENV

      - name: Debug Android SDK path
        run: |
          echo "ANDROID_HOME=$ANDROID_HOME"
          echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT"
          ls -la $HOME/android-sdk
          find $HOME/android-sdk -name "aidl"

      - name: Build APK
        run: |
          cd BratvaGame
          export ANDROID_HOME=$HOME/android-sdk
          export ANDROID_SDK_ROOT=$HOME/android-sdk
          export BUILDOZER_HOME=$HOME/buildozer-cache
          buildozer android debug
        env:
          ANDROID_HOME: /home/runner/android-sdk
          ANDROID_SDK_ROOT: /home/runner/android-sdk
          BUILDOZER_HOME: /home/runner/buildozer-cache

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: BratvaGame/bin/*.apk
