name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-for-android==2024.3.1
          pip install kivy==2.2.1

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git python3-dev ffmpeg libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev
          sudo apt-get install -y libffi-dev libssl-dev zlib1g-dev
          sudo apt-get install -y openjdk-17-jdk

      - name: Set up Android SDK
        run: |
          mkdir -p $HOME/android-sdk
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O commandlinetools.zip
          unzip commandlinetools.zip -d $HOME/android-sdk
          rm commandlinetools.zip
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$PATH:$ANDROID_HOME/cmdline-tools/bin
          yes | $ANDROID_HOME/cmdline-tools/bin/sdkmanager --sdk_root=$ANDROID_HOME "build-tools;33.0.0" "platforms;android-33" "platform-tools"
          echo "export ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "export PATH=$PATH:$ANDROID_HOME/cmdline-tools/bin" >> $GITHUB_ENV

      - name: Set up Android NDK
        run: |
          wget -q https://dl.google.com/android/repository/android-ndk-r23b-linux.zip -O android-ndk.zip
          unzip android-ndk.zip -d $HOME
          rm android-ndk.zip
          echo "export ANDROID_NDK=$HOME/android-ndk-r23b" >> $GITHUB_ENV

      - name: Debug Android SDK and NDK
        run: |
          echo "ANDROID_HOME=$ANDROID_HOME"
          echo "ANDROID_NDK=$ANDROID_NDK"
          ls -la $HOME/android-sdk
          ls -la $HOME/android-ndk-r23b
          find $HOME/android-sdk -name "adb"
          find $HOME/android-ndk-r23b -name "ndk-build"

      - name: Build APK with python-for-android
        run: |
          cd BratvaGame
          p4a apk --private . --package=org.bratva.bratva --name "Bratva 90s" --version 0.1 --bootstrap=sdl2 --requirements=python3,kivy --arch=armeabi-v7a --arch=arm64-v8a --minsdk=21 --ndk-api=21 --permission=INTERNET --icon=images/icon.png --debug --verbose
        env:
          ANDROID_HOME: /home/runner/android-sdk
          ANDROID_SDK_ROOT: /home/runner/android-sdk
          ANDROID_NDK: /home/runner/android-ndk-r23b

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: BratvaGame/*.apk
